language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm intstall
  - ./node_modules/.bin/bower install
  - ./node_modules/.bin/grunt coffee
  - ./node_modules/.bin/grunt copy:template

script:
  - ./node_modules/.bin/grunt karma:ci
